# Site settings
title: Alex Abraham - Resume
url: 'https://itsalexabraham.github.io'
baseurl: '/profile' # Change this to your repository name
description: Professional resume of Alex Abraham - Software Engineer II

# Build settings
markdown: kramdown

# Enable plugins
plugins:
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Sass
sass:
  sass_dir: _sass
  style: compressed
